- name: Copy VPN configs
  template: src=server.conf.j2 dest=/etc/wireguard/wg0.conf mode=770

- name: Start WireGuard
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
 
- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: wg-quick@wg0    